name: CI

on: [push]

jobs:
  mac:
    name: macOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode 12.4
      run: sudo xcode-select -s /Applications/Xcode_12.4.app
    - name: Run test
      run: make test
