name: CI

on: [push, pull_request]

jobs:
  mac:
    name: macOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode 12.4
      run: sudo xcode-select -s /Applications/Xcode_12.4.app
    - name: Run build
      run: make build
