name: CI

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app

jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - run: make test
  
  build:
    runs-on: macOS-latest
    steps:
    - uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}
    - run: echo "Build number is $BUILD_NUMBER"
