name: Licence

on: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - run: make build
    - run: make licenses
    - run: |
        if `git diff --quiet --exit-code` ; then
          git add App/MultiCalculator/Settings.bundle
          git commit -m"Run make licenses"
          git push origin HEAD
        fi
