name: testflight

# on:
#   push:
#     branches:
#       - main
on: [push]

jobs:
  deploy:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
          bundler-cache: true

      - run: make build
      - run: make licenses
      - uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}

      - run: echo "Build number is $BUILD_NUMBER"

      - name: deploy
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
          USERNAME: ${{ secrets.USERNAME }}
          PERSONAL_GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          BUILD_NUMBER: ${{ steps.buildnumber.outputs.build_number }}
        run: bundle exec fastlane deploy_testflight
